sonar.host.url=https://sonarcloud.io
sonar.organization=narv13
sonar.projectKey=NARV13_mlops-challenge
sonar.projectName=mlops-challenge

# Rutas de código y pruebas
sonar.sources=challenge
sonar.tests=tests
sonar.python.version=3.11

# Reportes de cobertura e inclusión
sonar.python.coverage.reportPaths=coverage.xml