# Llaves obligatorias de identificación del proyecto
sonar.organization=NARV13
sonar.projectKey=NARV13_mlops-challenge
sonar.projectName=mlops-challenge

# Rutas de los archivos fuente y de pruebas
sonar.sources=src
sonar.tests=tests

# Codificación del texto
sonar.sourceEncoding=UTF-8

# Vinculación del reporte de cobertura matemática generado por pytest
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones (Carpetas que SonarCloud NO debe evaluar)
sonar.exclusions=**/.venv/**, **/infra/terraform/terraform.exe, **/fake-credentials.json